services:
  rust:
    image: rust:latest
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: mendan
      POSTGRES_PASSWORD: password
      PGPASSWORD: Da#kkokumai833
      POSTGRES_DB: mendan
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
  redis:
    image: redis:6.2
    ports:
      - 6379:6379